
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module DE1_SOC(

	//////////// CLOCK //////////
	input 		          		CLOCK_50,
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,
	input 		          		CLOCK4_50,

	//////////// SEG7 //////////
	output		     [6:0]		HEX0,
	output		     [6:0]		HEX1,
	output		     [6:0]		HEX2,
	output		     [6:0]		HEX3,
	output		     [6:0]		HEX4,
	output		     [6:0]		HEX5,

	//////////// KEY //////////
	input 		     [3:0]		KEY,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// SW //////////
	input 		     [9:0]		SW
);


//=======================================================
//  REG/WIRE declarations
//=======================================================

localparam DW = 16;

wire clk;
wire resetn;
wire configure;
wire up;
wire down;
wire ready;
wire [15:0] bcd_out;
wire [15:0] bin_in;

wire tdi;
wire tdo;              
wire [1:0] ir_in;
// wire ir_out;
wire virtual_state_cdr;
wire virtual_state_sdr;
// wire virtual_state_e1d;
// wire virtual_state_pdr;
// wire virtual_state_e2d;
wire virtual_state_udr;
// wire virtual_state_cir;
// wire virtual_state_uir;
wire tck;              

wire [(DW-1):0] jtag_data;
reg [(DW-1):0] counter;


//=======================================================
//  Structural coding
//=======================================================

assign  clk = CLOCK_50;
assign  configure = ~KEY[0];
assign  up        = ~KEY[1];
assign  resetn    = KEY[2];
assign  ready     = ~KEY[3];

vjtag u_vjtag (
                    .tdi                (tdi),  // jtag.tdi
                    .tdo                (tdo),  //.tdo
                    .ir_in              (ir_in),  //.ir_in
                    .ir_out             (),  //.ir_out
                    .virtual_state_cdr  (virtual_state_cdr),  //.virtual_state_cdr
                    .virtual_state_sdr  (virtual_state_sdr),  //.virtual_state_sdr
                    .virtual_state_e1dr (),  //.virtual_state_e1dr
                    .virtual_state_pdr  (),  //.virtual_state_pdr
                    .virtual_state_e2dr (),  //.virtual_state_e2dr
                    .virtual_state_udr  (virtual_state_udr),  //.virtual_state_udr
                    .virtual_state_cir  (),  //.virtual_state_cir
                    .virtual_state_uir  (),  //.virtual_state_uir
                    .tck                (tck)   //  tck.clk
                    );

vjtag_interface  #(.DW(DW)) u_vjtag_interface (
                        .tck(tck),
                        .tdi(tdi),
                        .aclr(resetn),
                        .ir_in(ir_in),
                        .v_sdr(virtual_state_sdr),
                        .v_cdr(virtual_state_cdr),
                        .udr(virtual_state_udr),
                        .data_out(jtag_data),
                        .data_in(counter),
                        .tdo(tdo),
                        .debug_dr1(),
                        .debug_dr2()
                       );
							  
assign LEDR = counter[9:0];

always @(posedge clk or negedge resetn) begin
    if(!resetn) begin
        counter <= 0;
    end
    else begin
        counter <= jtag_data;
    end
end

endmodule
